### ISSUE TITLE
Excessive memory usage by daemon process

### ISSUE THREAD

**Issue by Self-Perfection** [CODeRUS/harbour-batteryoverlay#2]
Starting `harbour-batteryoverlay` process decreases free memory reported by `free` by more than 20 MiB. Way too much IMHO, I am reluctant to spend so much RAM on such a simple task. U know, RAM is always scarce on Jolla.

I see that daemon process and UI for changing settings are handled by the same binary `/usr/bin/harbour-batteryoverlay`. I wonder how much splitting `harbour-batteryoverlay` to daemon and config binaries and leaving only overlay related libraries linked with `harbour-batteryoverlay-daemon` would reduce RAM consumption by daemon process.

**Comment by CODeRUS** [comment]
No, it only using just 3 MB of RAM. All other used RAM is shared Qt libraries. Try to learn things you talking about better.

**Comment by Self-Perfection** [comment]
I insist that at least on my device it takes about 20 MiB of RAM.

I know that RSS field in `top` output is not reliable as it might include lots of shared memory. Looks like there is no tool to reliably estimate memory usage. So the best way is to run and check difference:

```
$ free; killall harbour-batteryoverlay; sleep 1; free
             total       used       free     shared    buffers     cached
Mem:        828696     782404      46292          0        844     213768
-/+ buffers/cache:     567792     260904
Swap:       793644     210668     582976
[1]+  Terminated              harbour-batteryoverlay
             total       used       free     shared    buffers     cached
Mem:        828696     759376      69320          0        844     213940
-/+ buffers/cache:     544592     284104
Swap:       793644     210668     582976
```

Check difference in `-/+ buffers/cache` field. It's about 25 MiB.
Ok, here is another measure:

```
$ devel-su pmap -d $(pidof harbour-batteryoverlay) | tail -1
Password: 
mapped: 136428K    writeable/private: 51568K    shared: 13232K
```

writable memory - 50 MB, shared - just 13MB.

Honestly I can't figure out how you measured 3MB of RAM usage. All the ways I can imagine to measure RAM usage give at least 10 times more.

**Comment by CODeRUS** [comment]
okay, current version using 10-11 MB of RAM. If you know what to improve to decrease this, you're welcome to send pull request to repository.
