### ISSUE TITLE
settings is not closed automatically when launching app

### ISSUE THREAD

**Issue by jean-clovis** [CODeRUS/harbour-batteryoverlay#3]
behaviour changed since last SFOS update, settings is kept in the launched app and need to be started again and then kille with swipe down :(

**Comment by CODeRUS** [comment]
Nothing is changing except new bugs. Go and ask Jolla to fix bugs in covers behaviour.

**Comment by jean-clovis** [comment]
ah ok, so this is a sfos bug, didn't think it was on their side :)

**Comment by clovis86** [comment]
So you find a workaround ! thanks :)
